### PR TITLE
Issue 516

### LINKED ISSUE #516: Smooth out the hangoutcards w/ border radius
Do you want to request a feature or report a bug?
**Feature**
What is the current behavior?
**Square**
What is the expected behavior?
**Smooth Square**
Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
**All**

### PR DESCRIPTION
**Pull request by grfraser**
Fixes #516 

Fixed the border radius to smooth out the cards and visual effect. Other part is at 6 because it overlaps the edge if not. Not sure if the package.json file or the .meteor/package and .meteor/release changes are important but you can ignore them if so or i can delete the changes. Let me know if this is an issue so I can fix it on my end otherwise I guess it is how it should be.

### CODE REVIEW

**Comment by grfraser** [comment]
thats beyond my head. i dont know about the webkit. but !important was already there so i just left it lol

**Comment by lpatmo** [comment]
@grfraser I learned about `-moz` and `-webkit` originally from https://css-tricks.com/almanac/properties/b/border-radius/. Hope the article is helpful :)

And yeah, I guessed you left it in there since it was already there; no worries!

**Comment by lpatmo** [comment]
(Also if you're unfamiliar with SASS, I think http://sass-lang.com/guide is really helpful... check out the "Mixin" section and their example actually shows `border-radius` :))

**Comment by lpatmo** [comment]
@grfraser Do you need help with writing the SASS line that's part of this issue? Let me know!

**Comment by nalbina** [comment]
What's left for this PR to be merged? Some styling?

**Comment by lpatmo** [comment]
Let's close this issue (making the borders rounded for now), pending issue #547.

**Pull request closed without merging**
