### PR TITLE
Issue 203 cards revised

### PR DESCRIPTION
**Pull request by lpatmo**
Finally.

### CODE REVIEW

**Comment by sergeant-q** [comment]
When you're not logged in, it appears the **Hangouts** link in the nav is showing up twice?
screen shot 2017-05-03 at 11 09 55 pm

New cards layout looks awesome! I do see one minor styling issue. It seems when the hangout description is lengthy, it bumps up against the details on the footer of the card. See screenshot below:

screen shot 2017-05-03 at 11 13 45 pm

**Comment by lpatmo** [comment]
@sergeant-q THANKS!! :) Fixed the first issue ("browse hangouts" link in nav). Looking into the second issue...

**Comment by lpatmo** [comment]
Made another commit to improve responsiveness (at least, don't think we should see the text overflowing anymore.)

**Comment by lpatmo** [comment]
As part of the cards redesign I also updated the post page:

screen shot 2017-05-04 at 2 51 13 am

**Pull request merged**
