### PR TITLE
changed font color, weight, and top margin of hangout post titles

### LINKED ISSUE #508: Remove text-align: justify on hangout posts and turn post titles black?
Like this:
screen shot 2017-05-06 at 10 18 48 pm

### PR DESCRIPTION
**Pull request by dmost1**
Fixes #508 

Resolves the feature request that requests the post title to be black, text-aligned: left, and bolded. I noticed, that when bolded, the text sometimes was displayed incorrectly. I increased the top margin by 10px, to counteract the bug.

### CODE REVIEW

**Comment by dmost1** [comment]
Awesome!

 Thanks, this is my first approved pull request!

**Comment by lpatmo** [comment]
Thank you for the edits, @dmost1! I switched out "600" instead of "bold" and removed a little of the margin-top spacing; if you pull, I think you might be able to those slight changes. I haven't seen the headline text displaying incorrectly here (or been able to recreate what you see before), but if it looks good, I'll merge this in. Thank you!

**Comment by dmost1** [comment]
No worries I'll work on it :)

**Comment by dmost1** [comment]
@lpatmo, I have just pulled the recent changes, and it looks good on my end!

**Comment by lpatmo** [comment]
Awesome, thank you @dmost1!

**Pull request merged**
