### PR TITLE
Changed color of "Click to load hangout" issue#697

### PR DESCRIPTION
**Pull request by gauravb12**
Solved Issue #697
Made the "Click to load hangout" text green.

Fixes #\<issue number\>.

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue above.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

Always follow the [contribution guidelines](https://github.com/codebuddiesdotorg/codebuddies/blob/master/contributing.md) when submitting a pull request.

### CODE REVIEW

**Comment by angelocordon** [comment]
Thanks for the PR @gauravb12, however, please read the whole thread in the issue and see: 
https://github.com/codebuddiesdotorg/codebuddies/issues/697#issuecomment-340352868

If you'd like to tackle the issue completely, let us know in the thread and I can assign you to it and add the `claim` tag.

**Comment by railsstudent** [comment]
I can work on it.

**Comment by angelocordon** [comment]
Thanks @railsstudent!

**Comment by lpatmo** [comment]
Fixed by @railsstudent in https://github.com/codebuddiesdotorg/codebuddies/pull/703 :)

**Pull request closed without merging**
