### PR TITLE
Issue 679 split handout sections

### LINKED ISSUE #679: UI: make clearer the difference between upcoming and past/completed hangouts
Noticed that for first-time users, it's not entirely clear that the slightly-more-greyed-out hangout cards refer to events that have ended.

Maybe we should separate out the /hangouts page into two sections, like:

Upcoming Events
// upcoming hangout events

Past Events
// completed hangout events

screen shot 2017-10-19 at 8 24 49 pm

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #679.

In the home of hangouts, divide hangouts into two sections, upcoming events and past events.
Similarly, hangouts are divided into upcoming events and past events in single study group

hangout_cards

single_study_group

@lpatmo  Please let me know if i have done more than i should in single study group.
@distalx  Please kindly code review my changes in study_group_hangouts.js. I am not sure if the implementation is efficient as the number of hangouts in a single study group increases considerably

Thanks.

### CODE REVIEW

**Comment by lpatmo** [comment]
Thank you @railsstudent! Will take a closer look tomorrow, but first thoughts that popped up to me:

- [ ] make h3s white so that they stand out better against the blue
- [ ] change first title to "Live and upcoming events", since there will be live events among them
- [ ] do not show title at top of there are no scheduled events

For the last one, I was expecting `{{#if hangouts}}` to work, but apparently there is still an object even if there are no live/upcoming hangouts, so that is puzzling. 

Will spend more time on this tomorrow night. Sorry!

**Comment by distalx** [comment]
Thanks for the PR! Here are some suggestions I hope you'll find helpful.

`loadHangouts` should contain all the hangout `return Hangouts.find({}, {sort: {start: -1}});`
we don’t have to filter hangouts at this stage, we will filter them inside template. So, we won’t be needing a `loadCompletedHangouts` function. you can remove that.

**inside the template …**
```
// this block will render current and upcoming hangouts
<div class="row margin-none" id="hangouts">
<h3 class="col-lg-12">{{_ "upcoming_events"}}</h3>
{{#each hangouts}}
	{{#unless isHangoutCompleted end}} // here we are filtering hangouts
		<div class="col-md-4">
		{{> hangoutCard}}
		</div>
	{{/unless}}
{{/each}}
</div>

//this block will render past hangots
<div class="row margin-none" id="past_hangouts">
<h3 class="col-lg-12">{{_ "past_events"}}</h3>
{{#each hangouts}}
	{{#if isHangoutCompleted end}} // here we are filtering hangouts
		<div class="col-md-4">
		{{> hangoutCard}}
		</div>
	{{/if}}
{{/each}}
</div>
```

**Comment by railsstudent** [comment]
@distalx How can i determine upcoming or past events exist and display or hide header ?

**Comment by distalx** [comment]
@railsstudent , we can hold hangout count for each block with the help of reactive-variable. 

Very roughly:

**template.js**
```
//inside onCreated

const now = new Date();
const hc = Hangouts.find({'end': { $gte : now }}, {sort: { start: 1 }}).count() || 0;
instance.liveOrUpComingHangout = new ReactiveVar(hc); //reactive variable

//inside helper 

liveOrUpComingHangout() {
 return Template.instance().liveOrUpComingHangout.get()
}
```

**template.html**
```
{{#if liveOrUpComingHangout}}
// this block will render current and upcoming hangouts
  [...]
{{/if}}
```

**Comment by railsstudent** [comment]
Done.
@lpatmo  @distalx  Please kindly review. thanks.

**Comment by lpatmo** [comment]
LGTM too. Thank you!

**Pull request merged**
