### PR TITLE
Upgraded the dependancies to the latest one

### PR DESCRIPTION
**Pull request by kanji-karanja**
The dependancies were abit outdated so added the new dependancies that were causing the app to crash now and then failing to start.

### CODE REVIEW

**Comment by lpatmo** [comment]
Thanks @kanji-karanja!

**Comment by distalx** [comment]
Hi @kanji-karanja, I'm not able to reproduce this issue.
what is the exact error message you're seeing?
Thanks.

**Comment by kanji-karanja** [comment]
There was an error that kept saying "App is crashing" and in the console it
would tell me to try to install something after which updating the
dependencies that were abit outdated resolved the issue and the app started
well

**Comment by lpatmo** [comment]
@kanji-karanja Sorry for the super slow reply. I haven't been able to reproduce this issue either. If you could, could you pull in the latest from `staging` and run the app again? And let us know if you still see the same problem? I'm hesitant to upgrade the dependencies in case it invisibly breaks features, since we don't have any tests.

**Pull request closed without merging**
