### PR TITLE
Issue 673 facebook channel

### LINKED ISSUE #673: Post text about virtual hangout and new study group creation to #facebook-group channel on Slack.
Folks on the Facebook Group at https://www.facebook.com/groups/TOPSTUDYGROUP/ don't often get notified about newly scheduled hangouts because we keep forgetting to cross-post/announce it there. 

I previously had set up a Zapier integration that would post new messages from the #announcements channel straight to the Facebook Group, but the integration wasn't working because it got confused by our emojis and layout:

screen shot 2017-10-18 at 11 58 12 pm

(The code behind this is in `server/slack/methods.js`)

I created a new #facebook-group channel on Slack, and was thinking we could start auto-posting simple text messages to this channel. Also, this channel would be a direct link to the Facebook Group, so if there were other Facebook-specific posts we wanted to make, this would be the channel for it. 

Specs:
1) Post a simple `@username has scheduled a new hangout on "TOPIC"! [link]` message to the #facebook-group channel whenever a new hangout has been scheduled.
2) Post a simple `New study group on CodeBuddies: "STUDY GROUP NAME" [link]` message to the Slack channel whenever a new study group is created.

This isn't a priority issue by any means, but more of a nice-to-have issue.

==
New contributors: please check out docs.codebuddies.org

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #673.

Send slack alert to #facebook-group channel when new hangout or new study group is created.
A new key-value pair "slack_facebook_alert_channel": "#facebook-group" is added to setting-development.json; therefore, this value needs to add to digital ocean droplet before production deployment

facebookgroupslack

### CODE REVIEW

**Comment by lpatmo** [comment]
Thank you @railsstudent! :)

I tested with Zapier, and looks good so far.

**Comment by lpatmo** [comment]
Perhaps we could make a small adjustment with the `new hangout` text (not set in stone; just thinking out loud):

screen shot 2017-10-31 at 12 10 37 am

**Comment by railsstudent** [comment]
@lpatmo This revised message sound better because it indicates possible action for whoever reads it in facebook.  I can change it after work tonight

**Comment by railsstudent** [comment]
@lpatmo  Message text updated. Please kindly review

**Pull request merged**
