### PR TITLE
Issue 720 tweet 280 characters

### LINKED ISSUE #720: Update 140 character limits to be 280
When a new study group or a new hangout is scheduled, it automatically gets tweeted out to https://twitter.com/codebuddiesmeet. We still have our max limits set to 140; we should update it to be 280 given Twitter's recent policy change.

### PR DESCRIPTION
**Pull request by railsstudent**
Fixes #720.

Tweet is sent when new learning is posted or new hangout is scheduled.
On the front-end, increase the character from 140 - 280 in study group learnt and learning status

In the backend, increase truncate count in tweet learning and tweet hangout.
For learning tweet, 250 characters are retained for learning status.
For hangout tweet, 160 characters are retained for hangout goal
 
hangout_learnt
learning_status

### CODE REVIEW

**Comment by nalbina** [comment]
Looks good! I am trying to get it to run locally, but if that works, it should be good to merge @linda @railsstudent

**Comment by railsstudent** [comment]
tweet is disabled in dev environment. need to turn on a flag in setting file to test sending tweets to codebuddies.org

**Comment by nalbina** [comment]
I feels a bit weird that the `I'm working on` is still limited to 140 whereas the `today I learned` has 280 characters. I know this is linked to what is sent to Twitter or not. but maybe we could align both?

**Comment by nalbina** [comment]
Which flag do I need to change? @railsstudent

**Comment by railsstudent** [comment]
isModeProduction from false to true

**Comment by railsstudent** [comment]
the i am working on/ i learnt will be removed in hangouts redesign, i would not bother to do further changes

**Comment by nalbina** [comment]
Tweets don't seem to turn up. :/

**Pull request merged**
