### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by salaxander**
This introduces the Dockerfile to run the app locally in a Docker container, that way contributors won't have to make any modifications to their systems (things like installing meteor etc.) :)

This is just a v1, I plan on making improvements to this, and I hope that others will too! In the meantime, I've updated the contributing.md file to include instructions on how to run the app with Docker.

### CODE REVIEW

**Comment by salaxander** [comment]
paging @lpatmo and @distalx for discussion :)

**Comment by lpatmo** [comment]
Yay! You made this look simple.

> After it's installed, run Docker, then in your terminal in the codebuddies directory type `docker build . -t codebuddies`. After the container builds, type `docker run -i -t -p 3000:3000 codebuddies`

I got stuck on getting the container to build after I did `brew install docker` on my mac running 10.10.4:

```
$ docker --version
Docker version 1.8.3, build f4bf5c7
$ docker build . -t codebuddies
docker: "build" requires 1 argument.
See 'docker build --help'.

Usage:	docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH
$ docker run -i -t -p 3000:3000 codebuddies
Post http://%2Fvar%2Frun%2Fdocker.sock/v1.20/containers/create: dial unix /var/run/docker.sock: connect: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

Is there anything obviously simple I'm doing run? I didn't run Docker yet, so maybe that's it.

**Comment by lpatmo** [comment]
Oh wait, I had an older version of virtualbox installed too, which is incompatible with docker. Hafta fix the install first.

**Comment by salaxander** [comment]
Yeah you'll have to run to Docker daemon for it to work. I've only ever installed the 'docker for Mac' from the website so I'm not sure if homebrew gives you anything different. Let me know how it goes :)

**Comment by distalx** [comment]
Hi @salaxander, 
Thank you for your pull request. And sorry for the delayed response.
Dockerization has become a thing. But IMHO it would be an overhead to used docker for codebuddies.
Meteor, in itself is a container - Out of the box it manages almost all the aspects of our development process.
Docker would have surly been useful only if we are to use meteor + other technologies.
Like, Meteor + SQL Database or some sort of data-broker or cacheing mechanism with (RabbitMQ, redis)  or anything which meteor dose’t provide by default. :)

**Comment by lpatmo** [comment]
Sorry for letting this PR linger for so long. Seems like the setup for the development environment (https://docs.codebuddies.org/contribution/development_environment.html -- two commands) is more simple than is required by setting up Docker, so am going to follow suggestions and close this issue. Thank you for opening it, though!

**Pull request closed without merging**
